### ISSUE TITLE
[sonar] The inetdata-parsers tools are not in the execution path, aborting normalization

### ISSUE THREAD

**Issue by icepaule** [fathom6/inetdata#2]
Hi hdm,

could you please help me with below error message to get that great tool running. I'd really love to use it, but I don't understand where to put the tools into the execution path.  :-)

:/opt/inetdata/bin# ./normalize.sh
2018-10-04 07:18:36 [normalize] Warning: Source wwwsio is disabled due to configuration
2018-10-04 07:18:36 [normalize] Warning: Source ct must be specified manually
2018-10-04 07:18:36 [normalize] Warning: Source censys_ipv4 must be specified manually
2018-10-04 07:18:36 [normalize] Warning: Source whoisxmlapi is disabled due to configuration
2018-10-04 07:18:36 [normalize] Warning: Source censys_certs must be specified manually
2018-10-04 07:18:36 [normalize] Warning: Source czds is disabled due to configuration
2018-10-04 07:18:36 [normalize] Warning: Source arin is disabled due to configuration
2018-10-04 07:18:36 [normalize] Warning: Source premiumdrops is disabled due to configuration
2018-10-04 07:18:36 [normalize] Normalize initiated with sources: govuk, sonar, rir, caida_prefix2as, gov
2018-10-04 07:18:36 [normalize] Error: Source govuk threw an exception: RuntimeError No dataset available for govuk ["/opt/inetdata/lib/inetdata/source/govuk.rb:173:in `latest_data'", "/opt/inetdata/lib/inetdata/source/govuk.rb:128:in `normalize'", "/opt/inetdata/bin/normalize.rb:80:in `block in <main>'", "/opt/inetdata/bin/normalize.rb:78:in `each'", "/opt/inetdata/bin/normalize.rb:78:in `<main>'"]
**2018-10-04 07:18:36 [normalize] [sonar] The inetdata-parsers tools are not in the execution path, aborting normalization**
2018-10-04 07:18:36 [normalize] Error: Source gov threw an exception: RuntimeError No dataset available for gov ["/opt/inetdata/lib/inetdata/source/gov.rb:129:in `latest_data'", "/opt/inetdata/lib/inetdata/source/gov.rb:90:in `normalize'", "/opt/inetdata/bin/normalize.rb:80:in `block in <main>'", "/opt/inetdata/bin/normalize.rb:78:in `each'", "/opt/inetdata/bin/normalize.rb:78:in `<main>'"]
2018-10-04 07:18:36 [normalize] Normalize completed with sources: govuk, sonar, rir, caida_prefix2as, gov
:/opt/inetdata/bin# ./normalize.sh

Thanks so much.

Marcus

**Comment by int0x80** [comment]
I installed them with the following command:

```
$ go get -v github.com/hdm/inetdata-parsers/...
$ inetdata-[tab][tab]
inetdata-arin-org2cidrs     inetdata-csv2mtbl           inetdata-ct2csv             inetdata-ct-tail            inetdata-json2mtbl          inetdata-zone2csv
inetdata-arin-xml2csv       inetdata-csvrollup          inetdata-ct2hostnames       inetdata-dns2mtbl           inetdata-lines2mtbl         
inetdata-arin-xml2json      inetdata-csvsplit           inetdata-ct2mtbl            inetdata-hostnames2domains  inetdata-sonardnsv2-split
```

My `PATH`s:

```
$ env | grep go
PATH=/home/user/.local/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/user/go/bin
GOPATH=/home/user/go
```

Go version is 1.15.

```
$ go version
go version go1.15 linux/amd64
```

Hope that helps!
